name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.Main
author: GabrielHD55
api-version: 1.18
description: ${project.description}
commands:
  partycrackers:
    usage: /<command>
    aliases:
      - partycracker
      - crackers
      - cracker